/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNewKeyDialog: typeof import('./src/components/AddNewKeyDialog/index.vue')['default']
    Button: typeof import('./src/components/Button/index.vue')['default']
    Divider: typeof import('./src/components/Divider/index.vue')['default']
    Input: typeof import('./src/components/Input/index.vue')['default']
    ScreenLoading: typeof import('./src/components/ScreenLoading/index.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    Tabs: typeof import('./src/components/Tabs/index.vue')['default']
    Textarea: typeof import('./src/components/Textarea/index.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip/index.vue')['default']
  }
}
